###############################################################################
# General Configuration
###############################################################################
version: 1.1.{build}

###############################################################################
# Environment Configuration
###############################################################################
image: Visual Studio 2019

configuration: 
 - Release
 - Debug
platform: 
  - x64
  - x86
environment:
  matrix:
  - solution_name: c-smallpt/c-smallpt.sln
  - solution_name: openmp-c-smallpt/c-smallpt.sln

###############################################################################
# Build Configuration
###############################################################################
build:
  parallel: true
  verbosity: normal

build_script:
  - msbuild %solution_name%
